# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>

sensor:
  - id: !extend battery_power
    filters:
      multiply: 10
  - id: !extend battery_2_power
    filters:
      multiply: 10
  - id: !extend pv1_power
    filters:
      multiply: 10
  - id: !extend pv2_power
    filters:
      multiply: 10
  - id: !extend pv3_power
    filters:
      multiply: 10
  - id: !extend pv4_power
    filters:
      multiply: 10
  - id: !extend battery_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_2_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_bms_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_bms_charging_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_bms_discharging_voltage
    filters:
      multiply: 0.1

number:
  - id: !extend generator_peak_shaving_power
    multiply: 0.1
    step: 10
  - id: !extend grid_peak_shaving_power
    multiply: 0.1
    step: 10
  - id: !extend max_sell_power
    multiply: 0.1
    step: 10
  - id: !extend max_solar_power
    multiply: 0.1
    step: 10
  - id: !extend zero_export_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_1_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_2_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_3_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_4_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_5_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_6_out_power
    multiply: 0.1
    step: 10
  - id: !extend battery_shutdown_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_restart_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_low_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_equalization_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_absorption_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_float_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_empty_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_grid_charging_start_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend battery_generator_charging_start_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend smartload_off_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend smartload_on_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_1_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_2_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_3_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_4_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_5_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_6_voltage
    multiply: 10
    step: 0.1
    min_value: 150
    max_value: 710
  - id: !extend time_of_use_all_voltage
    step: 0.1
    min_value: 150
    max_value: 710

switch:
  - id: !extend switch_time_of_use_1_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_2_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_3_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_4_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_5_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_6_sell
    disabled_by_default: false
