# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L1 Voltage"
    register_type: holding
    address: 644
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L2 Voltage"
    register_type: holding
    address: 645
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L3 Voltage"
    register_type: holding
    address: 646
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L1 Power"
    register_type: holding
    address: 650
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L2 Power"
    register_type: holding
    address: 651
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L3 Power"
    register_type: holding
    address: 652
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load Power"
    register_type: holding
    address: 653
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load Frequency"
    register_type: holding
    address: 655
    unit_of_measurement: "Hz"
    device_class: frequency
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Load Consumption"
    id: daily_load_consumption
    register_type: holding
    address: 526
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Consumption"
    id: total_consumption
    register_type: holding
    address: 527
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS L1 Power"
    register_type: holding
    address: 640
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS L2 Power"
    register_type: holding
    address: 641
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS L3 Power"
    register_type: holding
    address: 642
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS Power"
    register_type: holding
    address: 643
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: template
    name: "Power Losses"
    id: power_losses
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 1
    lambda: |-
      return (
        id(pv1_power).state +
        id(pv2_power).state +
        (id(pv3_power).state) +
        (id(pv4_power).state) +
        id(battery_power).state -
        id(generator_power_total).state -
        id(output_power).state
      );
    icon: "mdi:home-lightning-bolt"

  - platform: template
    name: "Daily Losses"
    id: daily_losses
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    lambda: |-
      return (
        id(daily_energy_bought).state +
        id(daily_pv_production).state +
        id(daily_generator_production).state +
        id(daily_battery_discharge).state -
        id(daily_energy_sold).state -
        id(daily_battery_charge).state -
        id(daily_load_consumption).state
      );
    icon: "mdi:home-lightning-bolt"

  - platform: template
    name: "Total Losses"
    id: total_losses
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    lambda: |-
      return (
        id(total_energy_bought).state +
        id(total_pv_production).state +
        id(total_generator_production).state +
        id(total_battery_discharge).state -
        id(total_energy_sold).state -
        id(total_battery_charge).state -
        id(total_consumption).state
      );
    icon: "mdi:home-lightning-bolt"

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "AC Load Relay Reserved"
    register_type: holding
    address: 552
    bitmask: 0x2
    icon: "mdi:toggle-switch-variant"
